# Generated by Django 4.2.4 on 2023-08-04 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(default='1691139194', editable=False, max_length=12, primary_key=True, serialize=False)),
                ('user_data', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.user')),
                ('user_flags', models.JSONField(default=dict)),
            ],
        ),
    ]
