# Generated by Django 4.2.4 on 2023-08-04 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(default='1691139197', editable=False, max_length=12, primary_key=True, serialize=False),
        ),
    ]
